[package]
name = "akula"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"
description = "Ethereum client based on turbo-geth client architecture"
license = "Apache-2.0"
default-run = "akula"

[dependencies]
akula-table-defs = { path = "src/kv/table-defs" }
anyhow = "1"
arrayref = "0.3"
async-stream = "0.3"
async-trait = "0.1"
auto_impl = "0.4"
byte-unit = "4"
static-bytes = { package = "bytes", version = "1" }
bytes = { package = "lifetimed-bytes", git = "https://github.com/vorot93/lifetimed-bytes" }
bytesize = "1"
clap = "2"
console-subscriber = { git = "https://github.com/tokio-rs/console" }
const_format = "0.2"
ethereum = "0.7"
ethereum-interfaces = { git = "https://github.com/ledgerwatch/interfaces", features = ["remotekv", "sentry"] }
ethereum-types = "0.11"
futures-core = "0.3"
hex = "0.4"
hex-literal = "0.3"
http = "0.2"
maplit = "1"
mdbx = { git = "https://github.com/vorot93/mdbx-rs" }
modular-bitfield = "0.11"
once_cell = "1"
pin-utils = "0.1"
rand = "0.8"
rlp = "0.5"
rlp-derive = "0.1"
roaring = "0.7"
secp256k1 = { version = "0.20", features = ["global-context"] }
serde = "1"
serde_json = "1"
sha3 = "0.9"
string = { git = "https://github.com/vorot93/string", branch = "update-bytes" }
structopt = "0.3"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
toml = "0.5"
tonic = { version = "0.4", default-features = false, features = ["codegen", "prost", "transport"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"

[build-dependencies]
akula-table-defs = { path = "src/kv/table-defs" }
quote = "1"

[dev-dependencies]
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
tokio = { version = "1", features = ["full"] }

[[bin]]
path = "bin/akula.rs"
name = "akula"

[[bin]]
path = "bin/akula-ddl.rs"
name = "akula-ddl"

[[bin]]
path = "bin/akula-rpc.rs"
name = "akula-rpc"

[[bin]]
path = "bin/akula-toolbox.rs"
name = "akula-toolbox"
