[package]
name = "ethdb"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"
description = "Rust implementation of turbo-geth database format"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
arrayref = "0.3"
async-stream = "0.3"
async-trait = "0.1"
auto_impl = "0.4"
bytes = { package = "lifetimed-bytes", git = "https://github.com/vorot93/lifetimed-bytes" }
educe = { version = "0.4", features = ["Debug"] }
ethereum = { git = "https://github.com/rust-blockchain/ethereum" }
ethereum-types = "0.11"
funty = "=1.1.0"
futures = "0.3"
hex = "0.4"
hex-literal = "0.3"
maplit = "1"
heed = { git = "https://github.com/vorot93/heed", branch = "dev", default-features = false, features = ["mdbx"] }
prost = "0.7"
rand = "0.8"
rlp = "0.5"
rlp-derive = "0.1"
roaring = "0.6"
serde = "1"
serde_json = "1"
sha3 = "0.9"
tokio = { version = "1", features = ["rt"] }
tokio-stream = "0.1"
tonic = { version = "0.4", default-features = false, features = ["codegen", "prost", "transport"] }
tracing = "0.1"

[build-dependencies]
tonic-build = "0.4"

[dev-dependencies]
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
tokio = { version = "1", features = ["full"] }
