[package]
name = "akula"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2018"
description = "Ethereum client based on turbo-geth client architecture"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
arrayref = "0.3"
async-stream = "0.3"
async-trait = "0.1"
bytes = { package = "lifetimed-bytes", git = "https://github.com/vorot93/lifetimed-bytes" }
ethereum = "0.7"
ethereum-interfaces = { git = "https://github.com/rust-ethereum/interfaces", default-features = false, features = ["remotekv"] }
ethereum-types = "0.11"
futures-core = "0.3"
hex = "0.4"
hex-literal = "0.3"
impls = "1"
maplit = "1"
mdbx = { git = "https://github.com/vorot93/mdbx-rs" }
mdbx-sys = { git = "https://github.com/vorot93/mdbx-rs" }
rand = "0.8"
rlp = "0.5"
rlp-derive = "0.1"
roaring = "0.6"
serde = "1"
serde_json = "1"
sha3 = "0.9"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tonic = { version = "0.4", default-features = false, features = ["codegen", "prost", "transport"] }
tracing = "0.1"

[dev-dependencies]
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
tokio = { version = "1", features = ["full"] }
