[package]
name = "akula"
version = "0.1.0"
authors = ["Artem Vorotnikov <artem@vorotnikov.me>"]
edition = "2021"
description = "Ethereum client based on turbo-geth client architecture"
license = "Apache-2.0"
default-run = "akula"

[dependencies]
anyhow = "1"
arrayref = "0.3"
arrayvec = "0.7"
async-recursion = "0.3"
async-stream = "0.3"
async-trait = "0.1"
auto_impl = "0.4"
bincode = "1"
byte-unit = "4"
bytes = "1"
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
bytesize = "1"
clap = "2"
console-subscriber = { git = "https://github.com/tokio-rs/console" }
crossterm = { version = "0.22", optional = true }
derive_more = "0.99"
educe = { version = "0.4", features = ["Debug", "Default"] }
ethereum-interfaces = { git = "https://github.com/ledgerwatch/interfaces", features = [
    "remotekv",
    "sentry",
] }
ethereum-types = "0.12"
evmodin = { git = "https://github.com/vorot93/evmodin", branch = "nightly" }
futures-core = "0.3"
futures-util = "0.3"
hash-db = "0.15"
hash256-std-hasher = "0.15"
hex = "0.4"
hex-literal = "0.3"
http = "0.2"
maplit = "1"
mdbx = { git = "https://github.com/vorot93/mdbx-rs" }
modular-bitfield = "0.11"
num-bigint = "0.4"
num-traits = "0.2"
once_cell = "1"
parking_lot = "0.11"
pin-utils = "0.1"
rand = "0.8"
rayon = "1"
ripemd160 = "0.9"
rlp = "0.5"
rlp-derive = "0.1"
roaring = "0.8"
secp256k1 = { version = "0.20", features = ["global-context", "recovery"] }
serde = "1"
serde_json = "1"
sha2 = "0.9"
sha3 = "0.9"
string = { git = "https://github.com/vorot93/string", branch = "update-bytes" }
structopt = "0.3"
strum = { version = "0.22", features = ["derive"] }
substrate-bn = "0.6"
tempfile = "3"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
toml = "0.5"
tonic = { version = "0.6", default-features = false, features = [
    "codegen",
    "prost",
    "transport",
] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
triehash = "0.8"
walkdir = "2"

[dev-dependencies]
bytes-literal = { git = "https://github.com/vorot93/bytes-literal" }
tokio = { version = "1", features = ["full"] }

[[bin]]
path = "bin/akula.rs"
name = "akula"

[[bin]]
path = "bin/akula-ddl.rs"
name = "akula-ddl"

[[bin]]
path = "bin/akula-rpc.rs"
name = "akula-rpc"

[[bin]]
path = "bin/akula-toolbox.rs"
name = "akula-toolbox"

[[bin]]
path = "bin/blockhashes_stage.rs"
name = "blockhashes_stage"

[[bin]]
path = "bin/consensus-tests.rs"
name = "consensus-tests"
